// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl8GeZphyv1zgtdHki8DggxCv5Yw0Tx5A',
    appId: '1:287306084427:web:fd52b52694d905afd39dce',
    messagingSenderId: '287306084427',
    projectId: 'newtoktask-8aeee',
    authDomain: 'newtoktask-8aeee.firebaseapp.com',
    storageBucket: 'newtoktask-8aeee.appspot.com',
    measurementId: 'G-X88EX5Z6LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_YXU5ZjhaycBPt4pbQZ52yAAWZVlnKPE',
    appId: '1:287306084427:android:1f3160d5d5a6aa7fd39dce',
    messagingSenderId: '287306084427',
    projectId: 'newtoktask-8aeee',
    storageBucket: 'newtoktask-8aeee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpRDGet__PZHoYl8xQT05ic0L4dhcLi6s',
    appId: '1:287306084427:ios:526d9ff03714149cd39dce',
    messagingSenderId: '287306084427',
    projectId: 'newtoktask-8aeee',
    storageBucket: 'newtoktask-8aeee.appspot.com',
    iosBundleId: 'com.example.newtokTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpRDGet__PZHoYl8xQT05ic0L4dhcLi6s',
    appId: '1:287306084427:ios:526d9ff03714149cd39dce',
    messagingSenderId: '287306084427',
    projectId: 'newtoktask-8aeee',
    storageBucket: 'newtoktask-8aeee.appspot.com',
    iosBundleId: 'com.example.newtokTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl8GeZphyv1zgtdHki8DggxCv5Yw0Tx5A',
    appId: '1:287306084427:web:b6ddbccabf1e157cd39dce',
    messagingSenderId: '287306084427',
    projectId: 'newtoktask-8aeee',
    authDomain: 'newtoktask-8aeee.firebaseapp.com',
    storageBucket: 'newtoktask-8aeee.appspot.com',
    measurementId: 'G-JGNWTN1XEF',
  );
}
